// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ2PsdERB9SJhoaVOtwDeNzpj3fchNzY0',
    appId: '1:20177254452:web:75e22b8a3f78f1ab01f261',
    messagingSenderId: '20177254452',
    projectId: 'flutter-iti-63a35',
    authDomain: 'flutter-iti-63a35.firebaseapp.com',
    storageBucket: 'flutter-iti-63a35.firebasestorage.app',
    measurementId: 'G-T4EDDBYGN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkeSjaFh_O3J7L3NJu9FVUJ2Y-Q1kh348',
    appId: '1:20177254452:android:8e41a8962482f11f01f261',
    messagingSenderId: '20177254452',
    projectId: 'flutter-iti-63a35',
    storageBucket: 'flutter-iti-63a35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBntSv3TVKgOjEv-jLBvWKB5K2s_a0UVhA',
    appId: '1:20177254452:ios:c178195bcd9f108f01f261',
    messagingSenderId: '20177254452',
    projectId: 'flutter-iti-63a35',
    storageBucket: 'flutter-iti-63a35.firebasestorage.app',
    iosBundleId: 'com.example.itiFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBntSv3TVKgOjEv-jLBvWKB5K2s_a0UVhA',
    appId: '1:20177254452:ios:c178195bcd9f108f01f261',
    messagingSenderId: '20177254452',
    projectId: 'flutter-iti-63a35',
    storageBucket: 'flutter-iti-63a35.firebasestorage.app',
    iosBundleId: 'com.example.itiFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ2PsdERB9SJhoaVOtwDeNzpj3fchNzY0',
    appId: '1:20177254452:web:3cd5892ef5a36b0301f261',
    messagingSenderId: '20177254452',
    projectId: 'flutter-iti-63a35',
    authDomain: 'flutter-iti-63a35.firebaseapp.com',
    storageBucket: 'flutter-iti-63a35.firebasestorage.app',
    measurementId: 'G-Q50Y27H7E1',
  );
}
